version: "3"
services:
  dev:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: vscode

    build:
      context: dev
      dockerfile: Dockerfile

    # ports:
      # - "4000:4000"

    volumes:
      - ..:/workspace:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

    command: /bin/sh -c "while sleep 1000; do :; done"
